[profile.v05]
src = "contracts/v0.5"
out = "out/v0.5"
test = "test/v0.5"
libs = ["lib/v0.5"]
auto_detect_solc = false
bytecode_hash = "none"
fuzz_runs = 256
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
solc = "0.5.17"
legacy = true
no_match_contract = "ForkTest"

[profile.v08]
src = "contracts/v0.8"
out = "out/v0.8"
test = "test/v0.8"
libs = ["lib/v0.8"]
auto_detect_solc = false
bytecode_hash = "none"
fuzz_runs = 256
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
solc = "0.8.19"
legacy = true
no_match_contract = "ForkTest"

[profile.ci]
fuzz_runs = 1_000
verbosity = 4

[profile.fork-tests]
no_match_contract = "_random" # in order to reset the no_match_contract
match_contract = "ForkTest"

[rpc_endpoints]
celo_mainnet="${CELO_MAINNET_RPC_URL}"
baklava="${BAKLAVA_RPC_URL}"
alfajores="${ALFAJORES_RPC_URL}"
